<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Str;

/**
 * ============================================================================
 * [LAB WORK 5] - AIOps Automated Incident Response Engine
 * This artisan command implements the final step in the AIOps pipeline:
 * automated remediation. It reads incidents generated by the Lab 2 detection
 * engine, applies response policies (defined in config/aiops.php), executes
 * simulated actions (restart, throttle, scale, alert), and logs every response
 * to storage/aiops/responses.json. If automated actions fail or anomalies
 * persist, the engine escalates to CRITICAL_ALERT.
 * ============================================================================
 */
class RunAIOpsResponse extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'aiops:respond
                            {--once : Run a single response cycle instead of continuous monitoring}
                            {--dry-run : Simulate actions without writing response logs}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Run the AIOps Automated Incident Response Engine.';

    /**
     * Tracks which incidents have already been responded to (by incident_id).
     * Prevents duplicate responses within the same engine session.
     */
    protected array $respondedIncidents = [];

    /**
     * Tracks retry counts per incident for escalation logic.
     */
    protected array $retryCounts = [];

    /**
     * Tracks cooldown expiry timestamps per incident type + endpoint combo.
     */
    protected array $cooldowns = [];

    /**
     * Accumulated response log entries for the current session.
     */
    protected array $responseLog = [];

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $this->printBanner();

        // Ensure storage directory exists
        $storageDir = storage_path('aiops');
        if (!is_dir($storageDir)) {
            mkdir($storageDir, 0755, true);
        }

        // Load existing response log if present
        $responsesFile = config('aiops.responses_file', storage_path('aiops/responses.json'));
        if (file_exists($responsesFile)) {
            $this->responseLog = json_decode(file_get_contents($responsesFile), true) ?: [];
        }

        if ($this->option('once')) {
            $this->info("Running single response cycle...\n");
            $this->runResponseCycle();
            $this->printSummary();
            return 0;
        }

        // Continuous monitoring mode
        $this->info("Starting continuous monitoring (Ctrl+C to stop)...\n");
        while (true) {
            $this->runResponseCycle();
            sleep(15);
        }

        return 0;
    }

    /**
     * Execute a single response cycle: read incidents, apply policies, log responses.
     */
    protected function runResponseCycle(): void
    {
        $this->line("--- Response Cycle --- " . now()->toDateTimeString());

        $incidents = $this->loadIncidents();
        if (empty($incidents)) {
            $this->line("  No incidents found.");
            return;
        }

        $openIncidents = array_filter($incidents, fn($i) => ($i['status'] ?? '') === 'OPEN');
        $newIncidents = array_filter($openIncidents, fn($i) => !isset($this->respondedIncidents[$i['incident_id']]));

        $this->line("  Total incidents: " . count($incidents)
            . " | Open: " . count($openIncidents)
            . " | Unprocessed: " . count($newIncidents));

        if (empty($newIncidents)) {
            $this->line("  All incidents already processed.");
            return;
        }

        $policies = config('aiops.policies', []);

        foreach ($newIncidents as $incident) {
            $this->processIncident($incident, $policies);
        }
    }

    /**
     * Process a single incident: look up policy, execute actions, handle escalation.
     */
    protected function processIncident(array $incident, array $policies): void
    {
        $incidentId   = $incident['incident_id'];
        $incidentType = $incident['incident_type'];
        $severity     = $incident['severity'];
        $endpoints    = $incident['affected_endpoints'] ?? [];

        $this->newLine();
        $this->warn("  Processing: [{$severity}] {$incidentType} — {$incidentId}");
        $this->line("    Endpoints: " . implode(', ', $endpoints));
        $this->line("    Detected:  " . ($incident['detected_at'] ?? 'unknown'));

        // Check cooldown
        $cooldownKey = $incidentType . '|' . implode(',', $endpoints);
        if (isset($this->cooldowns[$cooldownKey]) && time() < $this->cooldowns[$cooldownKey]) {
            $remaining = $this->cooldowns[$cooldownKey] - time();
            $this->line("    Cooldown active ({$remaining}s remaining). Skipping.");
            $this->respondedIncidents[$incidentId] = true;
            return;
        }

        // Look up response policy
        $policy = $policies[$incidentType] ?? null;
        if (!$policy) {
            $this->line("    No policy defined for {$incidentType}. Logging as unhandled.");
            $this->logResponse($incident, 'no_policy', 'skipped', "No automated response policy configured for incident type: {$incidentType}");
            $this->respondedIncidents[$incidentId] = true;
            return;
        }

        // Execute each action in the policy
        $allActionsSucceeded = true;
        foreach ($policy['actions'] as $actionDef) {
            $success = $this->executeAction($incident, $actionDef);
            if (!$success) {
                $allActionsSucceeded = false;
            }
        }

        // Set cooldown
        $cooldownSecs = $policy['cooldown'] ?? 60;
        $this->cooldowns[$cooldownKey] = time() + $cooldownSecs;

        // Escalation logic: if actions failed, increment retry counter
        if (!$allActionsSucceeded) {
            $retries = ($this->retryCounts[$incidentId] ?? 0) + 1;
            $this->retryCounts[$incidentId] = $retries;
            $maxRetries = $policy['max_retries'] ?? 3;

            if ($retries >= $maxRetries) {
                $this->escalate($incident, $policy);
            } else {
                $this->line("    Retry {$retries}/{$maxRetries}. Will re-attempt on next cycle.");
                // Don't mark as fully responded so it gets retried
                return;
            }
        }

        $this->respondedIncidents[$incidentId] = true;
    }

    /**
     * Execute (simulate) a single automated action.
     * Actions are simulated with realistic logging — no real services are modified.
     *
     * @return bool True if the action succeeded
     */
    protected function executeAction(array $incident, array $actionDef): bool
    {
        $actionType  = $actionDef['type'];
        $target      = $actionDef['target'];
        $description = $actionDef['description'] ?? '';
        $timeout     = $actionDef['timeout'] ?? 30;

        $this->line("    Executing: {$actionType} -> {$target}");
        $this->line("      {$description}");

        // Simulate the action with a deterministic outcome based on incident data
        // In production, these would call real infrastructure APIs.
        $result = $this->simulateAction($actionType, $target, $incident);

        $statusIcon = $result['success'] ? '[OK]' : '[FAIL]';
        $statusColor = $result['success'] ? 'info' : 'error';
        $this->{$statusColor}("      {$statusIcon} {$result['message']} ({$result['duration_ms']}ms)");

        // Log the response
        $this->logResponse(
            $incident,
            $actionType,
            $result['success'] ? 'success' : 'failed',
            $result['message']
        );

        return $result['success'];
    }

    /**
     * Simulate an automated action. Returns structured result.
     * Each action type has specific simulation logic that mimics real-world behavior.
     */
    protected function simulateAction(string $type, string $target, array $incident): array
    {
        $startMs = microtime(true);

        switch ($type) {
            case 'restart_service':
                // Simulate a service restart (always succeeds in simulation)
                usleep(100000); // 100ms simulated delay
                return [
                    'success'     => true,
                    'message'     => "Service '{$target}' restarted successfully. PID recycled, worker pool re-initialized.",
                    'duration_ms' => round((microtime(true) - $startMs) * 1000),
                ];

            case 'send_alert':
                // Simulate sending an alert notification
                usleep(50000); // 50ms
                $endpoints = implode(', ', $incident['affected_endpoints'] ?? []);
                return [
                    'success'     => true,
                    'message'     => "Alert dispatched to '{$target}' channel. Affected: {$endpoints}. Severity: {$incident['severity']}.",
                    'duration_ms' => round((microtime(true) - $startMs) * 1000),
                ];

            case 'throttle_traffic':
                // Simulate enabling rate limiting
                usleep(80000); // 80ms
                $endpointCount = count($incident['affected_endpoints'] ?? []);
                return [
                    'success'     => true,
                    'message'     => "Rate limiting enabled on {$endpointCount} endpoint(s). Max 10 req/s per client enforced.",
                    'duration_ms' => round((microtime(true) - $startMs) * 1000),
                ];

            case 'scale_service':
                // Simulate horizontal scaling
                usleep(200000); // 200ms
                return [
                    'success'     => true,
                    'message'     => "Scaled '{$target}' from 2 to 6 instances. Load balancer updated. Health checks passing.",
                    'duration_ms' => round((microtime(true) - $startMs) * 1000),
                ];

            case 'flush_cache':
                // Simulate cache flush
                usleep(30000); // 30ms
                return [
                    'success'     => true,
                    'message'     => "Application cache cleared. Route cache rebuilt. Config re-cached.",
                    'duration_ms' => round((microtime(true) - $startMs) * 1000),
                ];

            case 'enable_queue':
                // Simulate request queue activation
                usleep(60000); // 60ms
                return [
                    'success'     => true,
                    'message'     => "Request queue '{$target}' activated. Backpressure threshold set to 1000 pending requests.",
                    'duration_ms' => round((microtime(true) - $startMs) * 1000),
                ];

            case 'enable_circuit_breaker':
                // Simulate circuit breaker activation
                usleep(40000); // 40ms
                return [
                    'success'     => true,
                    'message'     => "Circuit breaker tripped for affected endpoints. Fast-fail (503) responses enabled for 60s.",
                    'duration_ms' => round((microtime(true) - $startMs) * 1000),
                ];

            default:
                return [
                    'success'     => false,
                    'message'     => "Unknown action type: {$type}",
                    'duration_ms' => 0,
                ];
        }
    }

    /**
     * Escalate an incident when automated remediation has been exhausted.
     */
    protected function escalate(array $incident, array $policy): void
    {
        $escalationType = $policy['escalation'] ?? 'CRITICAL_ALERT';
        $escalationConfig = config("aiops.escalation.{$escalationType}", []);

        $this->newLine();
        $this->error("    >>> ESCALATION: {$escalationType} <<<");
        $this->error("    Incident {$incident['incident_id']} — automated remediation exhausted.");
        $this->error("    Notifying: " . implode(', ', $escalationConfig['notify'] ?? ['ops-manager']));
        $this->error("    Channel: " . ($escalationConfig['channel'] ?? 'default'));
        $this->error("    " . ($escalationConfig['description'] ?? 'Immediate human intervention required.'));

        // Log the escalation as a response
        $this->logResponse(
            $incident,
            'escalation',
            'escalated',
            "CRITICAL_ALERT: Automated actions failed after max retries. "
                . "Escalated to: " . implode(', ', $escalationConfig['notify'] ?? ['ops-manager'])
                . " via " . ($escalationConfig['channel'] ?? 'default') . "."
        );
    }

    /**
     * Log a response record to the in-memory log and persist to disk.
     */
    protected function logResponse(array $incident, string $actionTaken, string $result, string $notes): void
    {
        $entry = [
            'response_id'   => (string) Str::uuid(),
            'incident_id'   => $incident['incident_id'],
            'incident_type' => $incident['incident_type'],
            'severity'      => $incident['severity'],
            'action_taken'  => $actionTaken,
            'timestamp'     => now()->toIso8601String(),
            'result'        => $result,
            'notes'         => $notes,
        ];

        $this->responseLog[] = $entry;

        // Persist to disk unless dry-run
        if (!$this->option('dry-run')) {
            $responsesFile = config('aiops.responses_file', storage_path('aiops/responses.json'));
            file_put_contents($responsesFile, json_encode($this->responseLog, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        }
    }

    /**
     * Load incidents from the JSON store written by the Lab 2 detection engine.
     */
    protected function loadIncidents(): array
    {
        $incidentsFile = config('aiops.incidents_file', storage_path('aiops/incidents.json'));
        if (!file_exists($incidentsFile)) {
            return [];
        }
        return json_decode(file_get_contents($incidentsFile), true) ?: [];
    }

    /**
     * Print a startup banner.
     */
    protected function printBanner(): void
    {
        $this->newLine();
        $this->info(str_repeat('=', 60));
        $this->info('  AIOps Automated Incident Response Engine');
        $this->info('  Lab Work 5 — Automation');
        $this->info(str_repeat('=', 60));

        $policies = config('aiops.policies', []);
        $this->line("  Loaded " . count($policies) . " response policies:");
        foreach ($policies as $type => $policy) {
            $actionNames = array_map(fn($a) => $a['type'], $policy['actions']);
            $this->line("    {$type} -> " . implode(', ', $actionNames));
        }
        $this->newLine();
    }

    /**
     * Print a summary of actions taken in this session.
     */
    protected function printSummary(): void
    {
        $this->newLine();
        $this->info(str_repeat('=', 60));
        $this->info('  RESPONSE SESSION SUMMARY');
        $this->info(str_repeat('=', 60));

        $sessionResponses = $this->responseLog;
        $totalActions = count($sessionResponses);
        $successes = count(array_filter($sessionResponses, fn($r) => $r['result'] === 'success'));
        $failures = count(array_filter($sessionResponses, fn($r) => $r['result'] === 'failed'));
        $escalations = count(array_filter($sessionResponses, fn($r) => $r['result'] === 'escalated'));
        $skipped = count(array_filter($sessionResponses, fn($r) => $r['result'] === 'skipped'));
        $uniqueIncidents = count(array_unique(array_column($sessionResponses, 'incident_id')));

        $this->line("  Incidents processed:  {$uniqueIncidents}");
        $this->line("  Total actions:        {$totalActions}");
        $this->info("  Successful:           {$successes}");
        if ($failures > 0) $this->error("  Failed:               {$failures}");
        if ($escalations > 0) $this->error("  Escalated:            {$escalations}");
        if ($skipped > 0) $this->line("  Skipped:              {$skipped}");

        $responsesFile = config('aiops.responses_file', storage_path('aiops/responses.json'));
        $this->newLine();
        $this->line("  Response log: {$responsesFile}");
        $this->info(str_repeat('=', 60));
        $this->newLine();
    }
}
