<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| [LAB WORK 1] - Web Routes & Prometheus /metrics Endpoint
|--------------------------------------------------------------------------
| This file exposes the /metrics endpoint which reads the counters and
| histograms generated by the TelemetryMiddleware. Prometheus scrapes
| this /metrics endpoint continuously.
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/metrics', [\App\Http\Controllers\ApiController::class, 'metrics']);
